/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.szamalk.mvc.view;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.szamalk.mvc.model.Partner;
import org.szamalk.mvc.model.PartnerModel;

/**
 *
 * @author feher.laszlo
 */
public class PartnerListExample extends javax.swing.JFrame {

    /**
     * Creates new form MVCPelda3
     */
    public PartnerListExample() {
        //testData();
        initComponents();
        testData();

        //nem lehet szerkeszteni a  mezőket
        this.nevTextField.setEditable(false);
        this.cimTextField.setEditable(false);
    }

    public void testData() {
        String[] telszamok = {"06-70-5555555", "06-20-55588888"};
        Partner p = new Partner(1, "T.K.", "Budapest Merítő utca 56.", new ArrayList<String>(Arrays.asList(telszamok)));

        String[] telszamok1 = {"06-70-5445555", "06-30-77588888"};
        Partner p1 = new Partner(2, "F.H.", "Budapest Kerítő utca 56.", new ArrayList<String>(Arrays.asList(telszamok1)));

        String[] telszamok2 = {"06-70-3335555", "06-30-4455888"};
        Partner p2 = new Partner(3, "Z.P.", "Budapest Kerek tér 6.", new ArrayList<String>(Arrays.asList(telszamok2)));

        String[] telszamok3 = {};
        Partner p3 = new Partner(4, "M.E.", "Budapest Kocka tér 9.", new ArrayList<String>(Arrays.asList(telszamok3)));

        if (jList1 != null && (this.jList1.getModel() instanceof PartnerModel)) {
            ((PartnerModel) this.jList1.getModel()).insertPartner(p);
            ((PartnerModel) this.jList1.getModel()).insertPartner(p1);
            ((PartnerModel) this.jList1.getModel()).insertPartner(p2);
            ((PartnerModel) this.jList1.getModel()).insertPartner(p3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        nevLabel = new javax.swing.JLabel();
        cimLabel = new javax.swing.JLabel();
        telefonszamokLabel = new javax.swing.JLabel();
        nevTextField = new javax.swing.JTextField();
        cimTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTFTelefon = new javax.swing.JTextField();
        jTFMobil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFFax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Partner");

        jList1.setModel(new PartnerModel());
        jList1.setCellRenderer(new PartnerView());
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        nevLabel.setText("Név:");

        cimLabel.setText("Cím:");

        telefonszamokLabel.setText("Telefonszámok:");

        cimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimTextFieldActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        jToggleButton1.setText("Új partner jozzáadása a listához");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Partner törlése");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Partner adatainak módosítása");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Telefon");

        jLabel2.setText("Mobil");

        jLabel3.setText("Fax");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nevLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cimTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(nevTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefonszamokLabel)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFFax)
                            .addComponent(jTFMobil)
                            .addComponent(jTFTelefon)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nevLabel)
                            .addComponent(nevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cimLabel)
                            .addComponent(cimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(telefonszamokLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton2)
                    .addComponent(jToggleButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cimTextFieldActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (this.jToggleButton1.isSelected()) {
            this.jToggleButton1.setText("Mentés");
            this.nevTextField.setEditable(true);
            this.cimTextField.setEditable(true);
            this.cimTextField.setText("");
            this.nevTextField.setText("");
            this.jList1.setEnabled(false);
            this.jToggleButton2.setEnabled(false);
            this.jButton2.setEnabled(false);
        } else {
            ((PartnerModel) this.jList1.getModel()).insertPartner(-1, this.nevTextField.getText(), this.cimTextField.getText(), "06-30", "06-31");
            this.jToggleButton1.setText("Új partner jozzáadása a listához");
            this.nevTextField.setEditable(false);
            this.cimTextField.setEditable(false);
            this.jList1.setEnabled(true);
            this.jToggleButton2.setEnabled(true);
            this.jButton2.setEnabled(true);
        }


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if (this.jList1.getSelectedValue() != null) {
            this.nevTextField.setText(((Partner) this.jList1.getSelectedValue()).getNev());
            this.cimTextField.setText(((Partner) this.jList1.getSelectedValue()).getCim());
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (this.jList1.getSelectedIndex() >= 0) {
            //dialogus ablak
            // yes no gombbal
            int request = JOptionPane.showConfirmDialog(this, "Valóban törölni szeretné " + ((Partner) this.jList1.getSelectedValue()).getNev() + " partnert?", "Figyelmeztetés", JOptionPane.YES_NO_OPTION);
            System.out.println(request);
            // ha a válasz igen azaz 0 ad vissza
            //akkor lehet törölni
            if (request == 0) {
                ((PartnerModel) this.jList1.getModel()).deletePartner(this.jList1.getSelectedIndex());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (this.jToggleButton2.isSelected()) {
            this.jToggleButton2.setText("Mentés");
            this.nevTextField.setEditable(true);
            this.cimTextField.setEditable(true);
            this.jList1.setEnabled(false);
            this.jToggleButton1.setEnabled(false);
            this.jButton2.setEnabled(false);

        } else {
            ((PartnerModel) this.jList1.getModel()).updatePartner(this.jList1.getSelectedIndex(), ((Partner) this.jList1.getSelectedValue()).getId(), this.nevTextField.getText(), this.cimTextField.getText(), "06-30", "06-31");
            this.jToggleButton2.setText("Partner adatainak módosítása");
            this.nevTextField.setEditable(false);
            this.cimTextField.setEditable(false);
            this.jList1.setEnabled(true);
            this.jToggleButton1.setEnabled(true);
            this.jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartnerListExample().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cimLabel;
    private javax.swing.JTextField cimTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFFax;
    private javax.swing.JTextField jTFMobil;
    private javax.swing.JTextField jTFTelefon;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel nevLabel;
    private javax.swing.JTextField nevTextField;
    private javax.swing.JLabel telefonszamokLabel;
    // End of variables declaration//GEN-END:variables
}
